/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 20-Nov-2015 12:44:58 PM 				*/
/*  DBMS       : SQL Server 2008 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_LuuTruDanhSachMonAnChoNhaBep_MonAn_SoLuong]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [LuuTruDanhSachMonAnNhaBepHoanThanh] DROP CONSTRAINT [FK_LuuTruDanhSachMonAnChoNhaBep_MonAn_SoLuong]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ÐatMon_Ban]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ÐatMon] DROP CONSTRAINT [FK_ÐatMon_Ban]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_NhanVien_ChucVuNhanVien]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [NhanVien] DROP CONSTRAINT [FK_NhanVien_ChucVuNhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_NhanVien_LoginNhanVien]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [NhanVien] DROP CONSTRAINT [FK_NhanVien_LoginNhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_KhaNangViTinhCuaNhanVien_NhanVien]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [KhaNangViTinhCuaNhanVien] DROP CONSTRAINT [FK_KhaNangViTinhCuaNhanVien_NhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_LichLamViec_LichCa]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [LichLamViec] DROP CONSTRAINT [FK_LichLamViec_LichCa]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_LichLamViec_Ban]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [LichLamViec] DROP CONSTRAINT [FK_LichLamViec_Ban]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_LichLamViec_NhanVien]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [LichLamViec] DROP CONSTRAINT [FK_LichLamViec_NhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ChiTietDatMon_ÐatMon]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ChiTietDatMon] DROP CONSTRAINT [FK_ChiTietDatMon_ÐatMon]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ChiTietDatMon_MonAn_SoLuong]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ChiTietDatMon] DROP CONSTRAINT [FK_ChiTietDatMon_MonAn_SoLuong]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_LuuTruDanhSachMonAnSoLuongKHoanThanh_MonAnDoUong_SoLuong]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [LuuTruDanhSachMonAnSoLuongKHoanThanh] DROP CONSTRAINT [FK_LuuTruDanhSachMonAnSoLuongKHoanThanh_MonAnDoUong_SoLuong]
GO

/* Drop Tables */

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[Ban]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [Ban]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[LuuTruDanhSachMonAnNhaBepHoanThanh]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [LuuTruDanhSachMonAnNhaBepHoanThanh]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[ÐatMon]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [ÐatMon]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[NhanVien]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [NhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[KhaNangViTinhCuaNhanVien]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [KhaNangViTinhCuaNhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[MonAnDoUong_SoLuong]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [MonAnDoUong_SoLuong]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[LichLamViec]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [LichLamViec]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[LichCa]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [LichCa]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[ChiTietDatMon]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [ChiTietDatMon]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[LoginNhanVien]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [LoginNhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[ChucVuNhanVien]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [ChucVuNhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[BanDanhSachMonAnNhaBepTrongNgay]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [BanDanhSachMonAnNhaBepTrongNgay]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[LuuTruDanhSachMonAnSoLuongKHoanThanh]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [LuuTruDanhSachMonAnSoLuongKHoanThanh]
GO

/* Create Tables */

CREATE TABLE [Ban]
(
	[ViTri] int NULL,
	[SoBan] int NOT NULL,
	[SoLuongKhach/Ban] int NULL,
	[TinhTrang] int NULL,
	[Ma] char(10) NULL
)
GO

CREATE TABLE [LuuTruDanhSachMonAnNhaBepHoanThanh]
(
	[NgayLamMon] date NOT NULL,
	[SoLuongMon] int NULL,
	[MaMon] char(10) NOT NULL
)
GO

CREATE TABLE [ÐatMon]
(
	[Ma] char(10) NOT NULL,
	[ThoiGian] datetime NULL,
	[TongTien] money NULL,
	[GhiChu] nvarchar(70) NULL,
	[SoBanChung] int NULL,
	[MaDatMon] char(10) NULL,
	[SoBan] int NULL,
	[SoLuongKhach] int NULL
)
GO

CREATE TABLE [NhanVien]
(
	[MaNV] char(10) NOT NULL,
	[TGBatDau] datetime NULL,
	[cmnd] char(10) NULL,
	[HoTen] nvarchar(50) NULL,
	[TinhTrang] bit NULL,
	[NgaySinh] datetime NULL,
	[GioiTinh] nvarchar(6) NULL,
	[LoaiNhanVien] nvarchar(50) NULL,
	[MaChucVu] int NULL
)
GO

CREATE TABLE [KhaNangViTinhCuaNhanVien]
(
	[MaNV] char(10) NOT NULL,
	[TenPhanMem] nvarchar(50) NOT NULL
)
GO

CREATE TABLE [MonAnDoUong_SoLuong]
(
	[TenMonAn] nvarchar(100) NOT NULL,
	[GiaTienHienTai] money NULL,
	[SoLuongTon] int NULL,
	[MaMon] char(10) NOT NULL,
	[ThucDonMon] bit NULL
)
GO

CREATE TABLE [LichLamViec]
(
	[MaNV] char(10) NOT NULL,
	[ThangNam] datetime NOT NULL,
	[Ca] int NOT NULL,
	[SoBan] int NULL
)
GO

CREATE TABLE [LichCa]
(
	[NamThang] datetime NOT NULL,
	[Ca] int NOT NULL,
	[Gio] datetime NULL,
	[Luong] money NULL
)
GO

CREATE TABLE [ChiTietDatMon]
(
	[MaDatMon] char(10) NULL,
	[MaMon] char(10) NULL,
	[SoLuong] int NULL,
	[GiaMotMon] money NULL,
	[ThoiGian] datetime NULL,
	[MaCT] char(10) NOT NULL,
	[GhiChu] nvarchar(50) NULL
)
GO

CREATE TABLE [LoginNhanVien]
(
	[MaNV] char(10) NOT NULL,
	[TenDangNhap] nvarchar(50) NULL,
	[MatKhau] varchar(8000) NULL
)
GO

CREATE TABLE [ChucVuNhanVien]
(
	[MaChucVu] int NOT NULL,
	[TenChucVu] varchar(50) NULL
)
GO

CREATE TABLE [BanDanhSachMonAnNhaBepTrongNgay]
(
	[MaMon] char(10) NULL,
	[TenMon] nvarchar(100) NULL,
	[ThoiGian] datetime NULL,
	[SoLuong] int NULL,
	[TinhTrang] bit NULL,
	[Ma] char(10) NULL,
	[IP] varchar(6) NULL
)
GO

CREATE TABLE [LuuTruDanhSachMonAnSoLuongKHoanThanh]
(
	[NgayLamMon] datetime NOT NULL,
	[SoLuongMon] int NULL,
	[MaMon] char(10) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Ban] 
 ADD CONSTRAINT [PK_Ban]
	PRIMARY KEY CLUSTERED ([SoBan])
GO

ALTER TABLE [LuuTruDanhSachMonAnNhaBepHoanThanh] 
 ADD CONSTRAINT [PK_DanhSachMonAnChoNhaBep]
	PRIMARY KEY CLUSTERED ([MaMon],[NgayLamMon])
GO

ALTER TABLE [ÐatMon] 
 ADD CONSTRAINT [PK_ÐatMon]
	PRIMARY KEY CLUSTERED ([Ma])
GO

ALTER TABLE [NhanVien] 
 ADD CONSTRAINT [PK_NhanVien]
	PRIMARY KEY CLUSTERED ([MaNV])
GO

ALTER TABLE [NhanVien] 
 ADD CONSTRAINT [UQ_NhanVien_cmd] UNIQUE NONCLUSTERED ([cmnd])
GO

ALTER TABLE [KhaNangViTinhCuaNhanVien] 
 ADD CONSTRAINT [PK_KhaNangViTinhCuaNhanVien]
	PRIMARY KEY CLUSTERED ([MaNV],[TenPhanMem])
GO

ALTER TABLE [MonAnDoUong_SoLuong] 
 ADD CONSTRAINT [PK_MonAn_SoLuong]
	PRIMARY KEY CLUSTERED ([MaMon])
GO

ALTER TABLE [LichLamViec] 
 ADD CONSTRAINT [PK_LichLamViec]
	PRIMARY KEY CLUSTERED ([MaNV],[ThangNam],[Ca])
GO

ALTER TABLE [LichCa] 
 ADD CONSTRAINT [PK_LichCa]
	PRIMARY KEY CLUSTERED ([NamThang],[Ca])
GO

ALTER TABLE [ChiTietDatMon] 
 ADD CONSTRAINT [PK_ChiTietDatMon]
	PRIMARY KEY CLUSTERED ([MaCT])
GO

ALTER TABLE [LoginNhanVien] 
 ADD CONSTRAINT [PK_LoginNhanVien]
	PRIMARY KEY CLUSTERED ([MaNV])
GO

ALTER TABLE [ChucVuNhanVien] 
 ADD CONSTRAINT [PK_ChucVuNhanVien]
	PRIMARY KEY CLUSTERED ([MaChucVu])
GO

ALTER TABLE [LuuTruDanhSachMonAnSoLuongKHoanThanh] 
 ADD CONSTRAINT [PK_LuuTruDanhSachMonAnSoLuongKHoanThanh]
	PRIMARY KEY CLUSTERED ([NgayLamMon],[MaMon])
GO

/* Create Foreign Key Constraints */

ALTER TABLE [LuuTruDanhSachMonAnNhaBepHoanThanh] ADD CONSTRAINT [FK_LuuTruDanhSachMonAnChoNhaBep_MonAn_SoLuong]
	FOREIGN KEY ([MaMon]) REFERENCES [MonAnDoUong_SoLuong] ([MaMon]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ÐatMon] ADD CONSTRAINT [FK_ÐatMon_Ban]
	FOREIGN KEY ([SoBan]) REFERENCES [Ban] ([SoBan]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [NhanVien] ADD CONSTRAINT [FK_NhanVien_ChucVuNhanVien]
	FOREIGN KEY ([MaChucVu]) REFERENCES [ChucVuNhanVien] ([MaChucVu]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [NhanVien] ADD CONSTRAINT [FK_NhanVien_LoginNhanVien]
	FOREIGN KEY ([MaNV]) REFERENCES [LoginNhanVien] ([MaNV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [KhaNangViTinhCuaNhanVien] ADD CONSTRAINT [FK_KhaNangViTinhCuaNhanVien_NhanVien]
	FOREIGN KEY ([MaNV]) REFERENCES [NhanVien] ([MaNV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [LichLamViec] ADD CONSTRAINT [FK_LichLamViec_LichCa]
	FOREIGN KEY ([ThangNam],[Ca]) REFERENCES [LichCa] ([NamThang],[Ca]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [LichLamViec] ADD CONSTRAINT [FK_LichLamViec_Ban]
	FOREIGN KEY ([SoBan]) REFERENCES [Ban] ([SoBan]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [LichLamViec] ADD CONSTRAINT [FK_LichLamViec_NhanVien]
	FOREIGN KEY ([MaNV]) REFERENCES [NhanVien] ([MaNV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ChiTietDatMon] ADD CONSTRAINT [FK_ChiTietDatMon_ÐatMon]
	FOREIGN KEY ([MaDatMon]) REFERENCES [ÐatMon] ([Ma]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ChiTietDatMon] ADD CONSTRAINT [FK_ChiTietDatMon_MonAn_SoLuong]
	FOREIGN KEY ([MaMon]) REFERENCES [MonAnDoUong_SoLuong] ([MaMon]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [LuuTruDanhSachMonAnSoLuongKHoanThanh] ADD CONSTRAINT [FK_LuuTruDanhSachMonAnSoLuongKHoanThanh_MonAnDoUong_SoLuong]
	FOREIGN KEY ([MaMon]) REFERENCES [MonAnDoUong_SoLuong] ([MaMon]) ON DELETE No Action ON UPDATE No Action
GO
