/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 02-Dec-2015 4:12:21 PM 				*/
/*  DBMS       : SQL Server 2008 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_LuuTruDanhSachMonAnChoNhaBep_MonAn_SoLuong]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [LuuTruDanhSachMonAnNhaBepHoanThanh] DROP CONSTRAINT [FK_LuuTruDanhSachMonAnChoNhaBep_MonAn_SoLuong]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ÐatMon_Ban]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [DatMon] DROP CONSTRAINT [FK_ÐatMon_Ban]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_NhanVien_ChucVuNhanVien]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [NhanVien] DROP CONSTRAINT [FK_NhanVien_ChucVuNhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_KhaNangViTinhCuaNhanVien_NhanVien]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [KhaNangViTinhCuaNhanVien] DROP CONSTRAINT [FK_KhaNangViTinhCuaNhanVien_NhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_LichLamViec_LichCa]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [LichLamViec] DROP CONSTRAINT [FK_LichLamViec_LichCa]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_LichLamViec_Ban]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [LichLamViec] DROP CONSTRAINT [FK_LichLamViec_Ban]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_LichLamViec_NhanVien]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [LichLamViec] DROP CONSTRAINT [FK_LichLamViec_NhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ChiTietDatMon_DatMon]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ChiTietDatMon] DROP CONSTRAINT [FK_ChiTietDatMon_DatMon]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ChiTietDatMon_MonAn_SoLuong]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ChiTietDatMon] DROP CONSTRAINT [FK_ChiTietDatMon_MonAn_SoLuong]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_LuuTruDanhSachMonAnSoLuongKHoanThanh_MonAnDoUong_SoLuong]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [LuuTruDanhSachMonAnSoLuongKHoanThanh] DROP CONSTRAINT [FK_LuuTruDanhSachMonAnSoLuongKHoanThanh_MonAnDoUong_SoLuong]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_LoginNhanVien_NhanVien]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [LoginNhanVien] DROP CONSTRAINT [FK_LoginNhanVien_NhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_SanPham_LoaiDonViTinh]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [SanPham] DROP CONSTRAINT [FK_SanPham_LoaiDonViTinh]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_NhaCungCap_DienThoai_NhaCungCap]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [NhaCungCap_DienThoai] DROP CONSTRAINT [FK_NhaCungCap_DienThoai_NhaCungCap]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_NhaCungCap_Email_NhaCungCap]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [NhaCungCap_Email] DROP CONSTRAINT [FK_NhaCungCap_Email_NhaCungCap]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_DatHang_NhaCungCap]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PhieuNhap] DROP CONSTRAINT [FK_DatHang_NhaCungCap]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_DatHang_NhanVien]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PhieuNhap] DROP CONSTRAINT [FK_DatHang_NhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_PhieuGiao_NhanVien]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PhieuNhan] DROP CONSTRAINT [FK_PhieuGiao_NhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_PhieuNhan_PhieuNhap]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PhieuNhan] DROP CONSTRAINT [FK_PhieuNhan_PhieuNhap]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ChiTietPhieuNhap_LoaiDonViTinh]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ChiTietPhieuNhap] DROP CONSTRAINT [FK_ChiTietPhieuNhap_LoaiDonViTinh]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ChiTietPhieuNhap_NguyenLieu]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ChiTietPhieuNhap] DROP CONSTRAINT [FK_ChiTietPhieuNhap_NguyenLieu]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ChiTietPhieuNhap_PhieuNhap]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ChiTietPhieuNhap] DROP CONSTRAINT [FK_ChiTietPhieuNhap_PhieuNhap]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ChiTietPhieuGiao_PhieuGiao]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ChiTietPhieuNhan] DROP CONSTRAINT [FK_ChiTietPhieuGiao_PhieuGiao]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ChiTietPhieuNhan_ChiTietPhieuNhap]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ChiTietPhieuNhan] DROP CONSTRAINT [FK_ChiTietPhieuNhan_ChiTietPhieuNhap]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ChiTietLamMon_MonAnDoUong_SoLuong]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ChiTietLamMon] DROP CONSTRAINT [FK_ChiTietLamMon_MonAnDoUong_SoLuong]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ChiTietLamMon_NguyenLieu]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ChiTietLamMon] DROP CONSTRAINT [FK_ChiTietLamMon_NguyenLieu]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_ChiTietLamMonMacDinh_LoaiDonViTinh]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [ChiTietLamMon] DROP CONSTRAINT [FK_ChiTietLamMonMacDinh_LoaiDonViTinh]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_LIchSuSanPham_SanPham]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [LuuTruSanPhamDaDung] DROP CONSTRAINT [FK_LIchSuSanPham_SanPham]
GO

/* Drop Tables */

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[Ban]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [Ban]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[LuuTruDanhSachMonAnNhaBepHoanThanh]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [LuuTruDanhSachMonAnNhaBepHoanThanh]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[DatMon]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [DatMon]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[NhanVien]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [NhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[KhaNangViTinhCuaNhanVien]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [KhaNangViTinhCuaNhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[MonAnDoUong]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [MonAnDoUong]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[LichLamViec]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [LichLamViec]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[LichCa]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [LichCa]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[ChiTietDatMon]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [ChiTietDatMon]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[ChucVuNhanVien]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [ChucVuNhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[LuuTruDanhSachMonAnSoLuongKHoanThanh]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [LuuTruDanhSachMonAnSoLuongKHoanThanh]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[LoginNhanVien]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [LoginNhanVien]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[SanPham]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [SanPham]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[NhaCungCap]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [NhaCungCap]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[NhaCungCap_DienThoai]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [NhaCungCap_DienThoai]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[NhaCungCap_Email]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [NhaCungCap_Email]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[PhieuNhap]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [PhieuNhap]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[PhieuNhan]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [PhieuNhan]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[ChiTietPhieuNhap]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [ChiTietPhieuNhap]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[ChiTietPhieuNhan]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [ChiTietPhieuNhan]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[ChiTietLamMon]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [ChiTietLamMon]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[LoaiDonViTinh]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [LoaiDonViTinh]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[LuuTruSanPhamDaDung]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [LuuTruSanPhamDaDung]
GO

/* Create Tables */

CREATE TABLE [Ban]
(
	[ViTri] nvarchar(50) NULL,
	[SoBan] int NOT NULL,
	[SoLuongKhach] int NULL,
	[TinhTrang] bit NULL    -- 1: da dat 0: chua dat
)
GO

CREATE TABLE [LuuTruDanhSachMonAnNhaBepHoanThanh]
(
	[NgayLamMon] date NOT NULL,
	[SoLuongMon] int NULL,
	[MaMon] char(10) NOT NULL
)
GO

CREATE TABLE [DatMon]
(
	[MaDatMon] char(10) NOT NULL,
	[ThoiGian] datetime NULL,
	[TongTien] money NULL,
	[GhiChu] nvarchar(70) NULL,
	[SoBanChung] int NULL,
	[SoBan] int NULL,
	[SoLuongKhach] int NULL,
	[MaNV] char(10) NULL
)
GO

CREATE TABLE [NhanVien]
(
	[MaNV] char(10) NOT NULL,
	[TGBatDau] datetime NULL,
	[cmnd] char(12) NULL,
	[HoTen] nvarchar(50) NULL,
	[TinhTrang] bit NULL,    -- 1: fulltime 0: parttime
	[NgaySinh] datetime NULL,
	[GioiTinh] nvarchar(6) NULL,
	[LoaiNhanVien] bit NULL,
	[MaChucVu] int NULL
)
GO

CREATE TABLE [KhaNangViTinhCuaNhanVien]
(
	[MaNV] char(10) NOT NULL,
	[TenPhanMem] nvarchar(50) NOT NULL
)
GO

CREATE TABLE [MonAnDoUong]
(
	[TenMon] nvarchar(100) NOT NULL,
	[GiaTienHienTai] money NULL,
	[MaMon] char(10) NOT NULL,
	[ThucDonMon] bit NULL    -- 1: Hien thi len thuc don mon 0: Khong hien thi
)
GO

CREATE TABLE [LichLamViec]
(
	[MaNV] char(10) NOT NULL,
	[ThangNam] datetime NOT NULL,
	[Ca] int NOT NULL,
	[SoBan] int NULL
)
GO

CREATE TABLE [LichCa]
(
	[NamThang] datetime NOT NULL,
	[Ca] int NOT NULL,
	[Gio] datetime NULL,
	[Luong] money NULL
)
GO

CREATE TABLE [ChiTietDatMon]
(
	[MaDatMon] char(10) NULL,
	[MaMon] char(10) NULL,
	[SoLuong] int NULL,
	[GiaMotMon] money NULL,
	[ThoiGian] datetime NOT NULL,
	[MaChuyen] char(10) NOT NULL,
	[ThanhTien] money NULL,
	[GhiChu] nvarchar(50) NULL
)
GO

CREATE TABLE [ChucVuNhanVien]
(
	[MaChucVu] int NOT NULL IDENTITY (1, 1),
	[TenChucVu] nvarchar(50) NULL
)
GO

CREATE TABLE [LuuTruDanhSachMonAnSoLuongKHoanThanh]
(
	[NgayLamMon] datetime NOT NULL,
	[SoLuongMon] int NULL,
	[MaMon] char(10) NOT NULL
)
GO

CREATE TABLE [LoginNhanVien]
(
	[MaNV] char(10) NOT NULL,
	[TenDN] varchar(50) NULL,
	[MatKhau] varchar(max) NULL
)
GO

CREATE TABLE [SanPham]
(
	[MaSP] char(10) NOT NULL,
	[TenSP] nvarchar(70) NULL,
	[SoLuongTon] int NULL,
	[MaDV] int NULL
)
GO

CREATE TABLE [NhaCungCap]
(
	[MaNCC] char(10) NOT NULL,
	[TenNCC] nvarchar(50) NULL,
	[DiaChi] nvarchar(60) NULL,
	[ChietKhau] decimal(3,2) NULL,
	[GhiChu] nvarchar(50) NULL
)
GO

CREATE TABLE [NhaCungCap_DienThoai]
(
	[MaNCC] char(10) NOT NULL,
	[SDT] char(15) NOT NULL
)
GO

CREATE TABLE [NhaCungCap_Email]
(
	[MaNCC] char(10) NOT NULL,
	[Email] varchar(50) NOT NULL
)
GO

CREATE TABLE [PhieuNhap]
(
	[MaPN] char(10) NOT NULL,
	[MaNV] char(10) NULL,
	[MaNCC] char(10) NULL,
	[NgayLap] date NULL,
	[NgayGiaoDK] date NULL,
	[TinhTrang] int NULL    -- 1: Hoan thanh 2: Chua duyet 3: Bi huy
)
GO

CREATE TABLE [PhieuNhan]
(
	[MaPG] char(10) NOT NULL,
	[MaPN] char(10) NULL,
	[MaNV] char(10) NULL,
	[TongTien] money NULL,
	[NgayLap] date NULL,
	[GhiChu] nvarchar(50) NULL
)
GO

CREATE TABLE [ChiTietPhieuNhap]
(
	[MaPN] char(10) NOT NULL,
	[MaSP] char(10) NOT NULL,
	[SoLuong] int NULL,
	[MaDV] int NULL,
	[DonGia] money NULL,
	[TongTien] money NULL
)
GO

CREATE TABLE [ChiTietPhieuNhan]
(
	[MaPG] char(10) NOT NULL,
	[MaSP] char(10) NOT NULL,
	[SoLuong] int NULL,
	[MaPN] char(10) NOT NULL
)
GO

CREATE TABLE [ChiTietLamMon]
(
	[MaMon] char(10) NOT NULL,
	[MaSP] char(10) NOT NULL,
	[MaDV] int NULL,
	[SoLuong] int NULL
)
GO

CREATE TABLE [LoaiDonViTinh]
(
	[MaDV] int NOT NULL IDENTITY (1, 1),
	[TenDV] nvarchar(8) NULL    -- Ðon vi tinh:  	- Chai 	- Lon 	- Kg 	- ml 	- Qua/Trai 	- Cai 	- Hop 	- Hu
)
GO

CREATE TABLE [LuuTruSanPhamDaDung]
(
	[STT] int NOT NULL IDENTITY (1, 1),
	[MaSP] char(10) NULL,
	[TenSP] nvarchar(50) NULL,
	[SoLuong] int NULL,
	[NgayDung] date NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Ban] 
 ADD CONSTRAINT [PK_Ban]
	PRIMARY KEY CLUSTERED ([SoBan])
GO

ALTER TABLE [LuuTruDanhSachMonAnNhaBepHoanThanh] 
 ADD CONSTRAINT [PK_DanhSachMonAnChoNhaBep]
	PRIMARY KEY CLUSTERED ([MaMon],[NgayLamMon])
GO

ALTER TABLE [DatMon] 
 ADD CONSTRAINT [PK_ÐatMon]
	PRIMARY KEY CLUSTERED ([MaDatMon])
GO

ALTER TABLE [NhanVien] 
 ADD CONSTRAINT [PK_NhanVien]
	PRIMARY KEY CLUSTERED ([MaNV])
GO

ALTER TABLE [NhanVien] 
 ADD CONSTRAINT [UQ_NhanVien_cmnd] CHECK (LEN(cmnd) = 9 OR LEN(cmnd) = 12)
GO

ALTER TABLE [NhanVien] 
 ADD CONSTRAINT [CK_GioiTinh] CHECK (GioiTinh in (Nam, Nu))
GO

ALTER TABLE [NhanVien] 
 ADD CONSTRAINT [CK_cmnd] CHECK (LEN(cmnd) = 9 OR LEN(cmnd) = 12)
GO

ALTER TABLE [KhaNangViTinhCuaNhanVien] 
 ADD CONSTRAINT [PK_KhaNangViTinhCuaNhanVien]
	PRIMARY KEY CLUSTERED ([MaNV],[TenPhanMem])
GO

ALTER TABLE [MonAnDoUong] 
 ADD CONSTRAINT [PK_MonAn_SoLuong]
	PRIMARY KEY CLUSTERED ([MaMon])
GO

ALTER TABLE [LichLamViec] 
 ADD CONSTRAINT [PK_LichLamViec]
	PRIMARY KEY CLUSTERED ([MaNV],[ThangNam],[Ca])
GO

ALTER TABLE [LichCa] 
 ADD CONSTRAINT [PK_LichCa]
	PRIMARY KEY CLUSTERED ([NamThang],[Ca])
GO

ALTER TABLE [ChiTietDatMon] 
 ADD CONSTRAINT [PK_ChiTietDatMon]
	PRIMARY KEY CLUSTERED ([ThoiGian],[MaChuyen])
GO

ALTER TABLE [ChucVuNhanVien] 
 ADD CONSTRAINT [PK_ChucVuNhanVien]
	PRIMARY KEY CLUSTERED ([MaChucVu])
GO

ALTER TABLE [LuuTruDanhSachMonAnSoLuongKHoanThanh] 
 ADD CONSTRAINT [PK_LuuTruDanhSachMonAnSoLuongKHoanThanh]
	PRIMARY KEY CLUSTERED ([NgayLamMon],[MaMon])
GO

ALTER TABLE [LoginNhanVien] 
 ADD CONSTRAINT [PK_LoginNhanVien]
	PRIMARY KEY CLUSTERED ([MaNV])
GO

ALTER TABLE [SanPham] 
 ADD CONSTRAINT [PK_NguyenLieu]
	PRIMARY KEY CLUSTERED ([MaSP])
GO

ALTER TABLE [NhaCungCap] 
 ADD CONSTRAINT [PK_NhaCungCap]
	PRIMARY KEY CLUSTERED ([MaNCC])
GO

ALTER TABLE [NhaCungCap_DienThoai] 
 ADD CONSTRAINT [PK_NhaCungCap_DienThoai]
	PRIMARY KEY CLUSTERED ([MaNCC],[SDT])
GO

ALTER TABLE [NhaCungCap_Email] 
 ADD CONSTRAINT [PK_NhaCungCap_Email]
	PRIMARY KEY CLUSTERED ([MaNCC],[Email])
GO

ALTER TABLE [PhieuNhap] 
 ADD CONSTRAINT [PK_PhieuNhap]
	PRIMARY KEY CLUSTERED ([MaPN])
GO

ALTER TABLE [PhieuNhan] 
 ADD CONSTRAINT [PK_PhieuGiao]
	PRIMARY KEY CLUSTERED ([MaPG])
GO

ALTER TABLE [ChiTietPhieuNhap] 
 ADD CONSTRAINT [PK_ChiTietPhieuNhap]
	PRIMARY KEY CLUSTERED ([MaPN],[MaSP])
GO

ALTER TABLE [ChiTietPhieuNhan] 
 ADD CONSTRAINT [PK_ChiTietPhieuGiao]
	PRIMARY KEY CLUSTERED ([MaPG],[MaSP],[MaPN])
GO

ALTER TABLE [ChiTietLamMon] 
 ADD CONSTRAINT [PK_ChiTietLamMon]
	PRIMARY KEY CLUSTERED ([MaMon],[MaSP])
GO

ALTER TABLE [LoaiDonViTinh] 
 ADD CONSTRAINT [PK_LoaiDonViTinh]
	PRIMARY KEY CLUSTERED ([MaDV])
GO

ALTER TABLE [LuuTruSanPhamDaDung] 
 ADD CONSTRAINT [PK_LIchSuSanPham]
	PRIMARY KEY CLUSTERED ([STT])
GO

/* Create Foreign Key Constraints */

ALTER TABLE [LuuTruDanhSachMonAnNhaBepHoanThanh] ADD CONSTRAINT [FK_LuuTruDanhSachMonAnChoNhaBep_MonAn_SoLuong]
	FOREIGN KEY ([MaMon]) REFERENCES [MonAnDoUong] ([MaMon]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DatMon] ADD CONSTRAINT [FK_ÐatMon_Ban]
	FOREIGN KEY ([SoBan]) REFERENCES [Ban] ([SoBan]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [NhanVien] ADD CONSTRAINT [FK_NhanVien_ChucVuNhanVien]
	FOREIGN KEY ([MaChucVu]) REFERENCES [ChucVuNhanVien] ([MaChucVu]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [KhaNangViTinhCuaNhanVien] ADD CONSTRAINT [FK_KhaNangViTinhCuaNhanVien_NhanVien]
	FOREIGN KEY ([MaNV]) REFERENCES [NhanVien] ([MaNV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [LichLamViec] ADD CONSTRAINT [FK_LichLamViec_LichCa]
	FOREIGN KEY ([ThangNam],[Ca]) REFERENCES [LichCa] ([NamThang],[Ca]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [LichLamViec] ADD CONSTRAINT [FK_LichLamViec_Ban]
	FOREIGN KEY ([SoBan]) REFERENCES [Ban] ([SoBan]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [LichLamViec] ADD CONSTRAINT [FK_LichLamViec_NhanVien]
	FOREIGN KEY ([MaNV]) REFERENCES [NhanVien] ([MaNV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ChiTietDatMon] ADD CONSTRAINT [FK_ChiTietDatMon_DatMon]
	FOREIGN KEY ([MaDatMon]) REFERENCES [DatMon] ([MaDatMon]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ChiTietDatMon] ADD CONSTRAINT [FK_ChiTietDatMon_MonAn_SoLuong]
	FOREIGN KEY ([MaMon]) REFERENCES [MonAnDoUong] ([MaMon]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [LuuTruDanhSachMonAnSoLuongKHoanThanh] ADD CONSTRAINT [FK_LuuTruDanhSachMonAnSoLuongKHoanThanh_MonAnDoUong_SoLuong]
	FOREIGN KEY ([MaMon]) REFERENCES [MonAnDoUong] ([MaMon]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [LoginNhanVien] ADD CONSTRAINT [FK_LoginNhanVien_NhanVien]
	FOREIGN KEY ([MaNV]) REFERENCES [NhanVien] ([MaNV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [SanPham] ADD CONSTRAINT [FK_SanPham_LoaiDonViTinh]
	FOREIGN KEY ([MaDV]) REFERENCES [LoaiDonViTinh] ([MaDV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [NhaCungCap_DienThoai] ADD CONSTRAINT [FK_NhaCungCap_DienThoai_NhaCungCap]
	FOREIGN KEY ([MaNCC]) REFERENCES [NhaCungCap] ([MaNCC]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [NhaCungCap_Email] ADD CONSTRAINT [FK_NhaCungCap_Email_NhaCungCap]
	FOREIGN KEY ([MaNCC]) REFERENCES [NhaCungCap] ([MaNCC]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [PhieuNhap] ADD CONSTRAINT [FK_DatHang_NhaCungCap]
	FOREIGN KEY ([MaNCC]) REFERENCES [NhaCungCap] ([MaNCC]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [PhieuNhap] ADD CONSTRAINT [FK_DatHang_NhanVien]
	FOREIGN KEY ([MaNV]) REFERENCES [NhanVien] ([MaNV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [PhieuNhan] ADD CONSTRAINT [FK_PhieuGiao_NhanVien]
	FOREIGN KEY ([MaNV]) REFERENCES [NhanVien] ([MaNV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [PhieuNhan] ADD CONSTRAINT [FK_PhieuNhan_PhieuNhap]
	FOREIGN KEY ([MaPN]) REFERENCES [PhieuNhap] ([MaPN]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ChiTietPhieuNhap] ADD CONSTRAINT [FK_ChiTietPhieuNhap_LoaiDonViTinh]
	FOREIGN KEY ([MaDV]) REFERENCES [LoaiDonViTinh] ([MaDV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ChiTietPhieuNhap] ADD CONSTRAINT [FK_ChiTietPhieuNhap_NguyenLieu]
	FOREIGN KEY ([MaSP]) REFERENCES [SanPham] ([MaSP]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ChiTietPhieuNhap] ADD CONSTRAINT [FK_ChiTietPhieuNhap_PhieuNhap]
	FOREIGN KEY ([MaPN]) REFERENCES [PhieuNhap] ([MaPN]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ChiTietPhieuNhan] ADD CONSTRAINT [FK_ChiTietPhieuGiao_PhieuGiao]
	FOREIGN KEY ([MaPG]) REFERENCES [PhieuNhan] ([MaPG]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ChiTietPhieuNhan] ADD CONSTRAINT [FK_ChiTietPhieuNhan_ChiTietPhieuNhap]
	FOREIGN KEY ([MaPN],[MaSP]) REFERENCES [ChiTietPhieuNhap] ([MaPN],[MaSP]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ChiTietLamMon] ADD CONSTRAINT [FK_ChiTietLamMon_MonAnDoUong_SoLuong]
	FOREIGN KEY ([MaMon]) REFERENCES [MonAnDoUong] ([MaMon]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ChiTietLamMon] ADD CONSTRAINT [FK_ChiTietLamMon_NguyenLieu]
	FOREIGN KEY ([MaSP]) REFERENCES [SanPham] ([MaSP]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ChiTietLamMon] ADD CONSTRAINT [FK_ChiTietLamMonMacDinh_LoaiDonViTinh]
	FOREIGN KEY ([MaDV]) REFERENCES [LoaiDonViTinh] ([MaDV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [LuuTruSanPhamDaDung] ADD CONSTRAINT [FK_LIchSuSanPham_SanPham]
	FOREIGN KEY ([MaSP]) REFERENCES [SanPham] ([MaSP]) ON DELETE No Action ON UPDATE No Action
GO

/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', '1: da dat 0: chua dat', 'Schema', [dbo], 'table', [Ban], 'column', [TinhTrang]
GO

EXEC sp_addextendedproperty 'MS_Description', '1: fulltime 0: parttime', 'Schema', [dbo], 'table', [NhanVien], 'column', [TinhTrang]
GO

EXEC sp_addextendedproperty 'MS_Description', '1: Hien thi len thuc don mon 0: Khong hien thi', 'Schema', [dbo], 'table', [MonAnDoUong], 'column', [ThucDonMon]
GO

EXEC sp_addextendedproperty 'MS_Description', '1: Hoan thanh 2: Chua duyet 3: Bi huy', 'Schema', [dbo], 'table', [PhieuNhap], 'column', [TinhTrang]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Ðon vi tinh:  	- Chai 	- Lon 	- Kg 	- ml 	- Qua/Trai 	- Cai 	- Hop 	- Hu', 'Schema', [dbo], 'table', [LoaiDonViTinh], 'column', [TenDV]
GO
